channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.1.1
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - packaging==24.1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
